### ISSUE TITLE
Student Model Mapping Invalid

### ISSUE THREAD

**Issue by Deltatiger** [ramvijay/VivaManagementSystem#21] opened 2017-01-14 13:06 UTC
Postal code contains Short URL and vice versa.

@Prsna23 Can I directly swap the entries in the Models file without causing any backlash ?

**Comment by Prsna23** [comment] 2017-01-16 04:20
What kind of entries? Can you be more specific? Postal Code and Short URL in students model?

**Comment by Deltatiger** [comment] 2017-01-16 08:37
![vms_db_mismapping](https://cloud.githubusercontent.com/assets/1459811/21975861/11dfed58-dbf5-11e6-881e-6f7f44c790e8.png)
@Prsna23

**Comment by Prsna23** [comment] 2017-01-16 08:39
Oops. I think the problem is with the spreadsheet_module.py in the utils folder. The data to db is sent incorrectly. Please check the file.

**Comment by Deltatiger** [comment] 2017-01-16 08:41
Will change the file with the next update. It is not being used anywhere
right now is it ?

**Comment by Prsna23** [comment] 2017-01-16 09:01
No its not used anywhere I guess. If there's any conflict, then let's change it.

**Comment by Prsna23** [comment] 2017-01-17 04:34
I have made the changes myself. See the commit message. Clear the student db and then try. It will work properly now. I am closing the issue.

**Closed as completed by Prsna23** 2017-01-17 04:34 UTC
Labels: bug, help wanted

**Comment by Deltatiger** [comment] 2017-02-20 14:25
Completely fixed in 17d037920e6aa0ba45a7f5a07fa13499c641dcbb.
